<a href="https://colab.research.google.com/github/Jeonkyoungyong/bigdata/blob/main/5%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C3_reshape()_method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
temp = np.arange(48)

array_3d = temp.reshape((4, 3, 4))
array_2d = temp.reshape((6,8))
print('3차원배열 =')
print(array_3d)

print('2차원배열 =')
print(array_2d)

3차원배열 =
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]

 [[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
2차원배열 =
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]]
