<a href="https://colab.research.google.com/github/Jeonkyoungyong/bigdata/blob/main/5%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C2_%EC%9E%84%EC%9D%98_3%EC%B0%A8%EC%97%B4_%EB%B0%B0%EC%97%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def random_int_generator(low, high):
  return np.random.randint(low, high, size=(3, 3, 6))

array = random_int_generator(0, 21)

print(array)

[[[16  8 16  3 19  2]
  [ 0  5 12  6 15 12]
  [17 20 17 10 17  1]]

 [[12  7 18  6 19 16]
  [ 7 17 12  9  9 17]
  [ 6  1 14  2 14  1]]

 [[19 19  2  5 14 19]
  [ 6 12  4 12 12  4]
  [ 9  1  6 12 13  4]]]


In [2]:
import numpy as np

def random_int_generator(low, high):
  return np.random.randint(low, high, size=(5, 6))

array = random_int_generator(0, 101)

print(array)

[[ 1 27 96 10 90 92]
 [ 1 41 61  8 32 27]
 [98 73 64 31 17  5]
 [46 19 56 65  4 55]
 [86 17 52 14 12 55]]
